using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
using System.Text;

// Autogenerated on : 22-6-2020 17:17:07 by afas-cli

namespace DutchGrit.Afas.BuiltIn.Entities
{
    [ConnectorName("AfasClient_FreeTables")] 
    public class AfasClientFreeTables : IGetEntity 
    {
        public AfasClientFreeTables() { }

        /// <summary>
        /// Product
        /// </summary>
        [JsonPropertyName("Product")]
        public virtual string Product { get; set; }


        /// <summary>
        /// Tabel
        /// </summary>
        [JsonPropertyName("Tabel")]
        public virtual string Tabel { get; set; }


        /// <summary>
        /// Omschrijving
        /// </summary>
        [JsonPropertyName("Omschrijving")]
        public virtual string Omschrijving { get; set; }


        /// <summary>
        /// Lengte code
        /// </summary>
        [JsonPropertyName("Lengte_code")]
        public virtual int? Lengte_code { get; set; }


        /// <summary>
        /// Lengte omschrijving
        /// </summary>
        [JsonPropertyName("Lengte_omschrijving")]
        public virtual int? Lengte_omschrijving { get; set; }


        /// <summary>
        /// AantalRecords
        /// </summary>
        [JsonPropertyName("AantalRecords")]
        public virtual int? AantalRecords { get; set; }
    }
}
