using System.Text.Json.Serialization;

// Autogenerated on : 22-6-2020 17:17:07 by afas-cli

namespace DutchGrit.Afas.BuiltIn.Entities
{
    [ConnectorName("AfasClient_FreeTableRecords")] 
    public class AfasClientFreeTableRecords : IGetEntity 
    {
        public AfasClientFreeTableRecords() { }

        /// <summary>
        /// Product
        /// </summary>
        [JsonPropertyName("Product")]
        public virtual string Product { get; set; }


        /// <summary>
        /// Tabel
        /// </summary>
        [JsonPropertyName("Tabel")]
        public virtual string Tabel { get; set; }


        /// <summary>
        /// Interne code
        /// </summary>
        [JsonPropertyName("Interne_code")]
        public virtual string Interne_code { get; set; }


        /// <summary>
        /// Omschrijving
        /// </summary>
        [JsonPropertyName("Omschrijving")]
        public virtual string Omschrijving { get; set; }


        /// <summary>
        /// Tabelwaarde code
        /// </summary>
        [JsonPropertyName("Tabelwaarde_code")]
        public virtual string Tabelwaarde_code { get; set; }


        /// <summary>
        /// Vrije tabelwaarde
        /// </summary>
        [JsonPropertyName("Tabelwaarde_vrij")]
        public virtual bool? Tabelwaarde_vrij { get; set; }


        /// <summary>
        /// Geblokkeerd
        /// </summary>
        [JsonPropertyName("Geblokkeerd")]
        public virtual bool? Geblokkeerd { get; set; }

    }
}
